
run:
	docker run -it -p 2181:2181 -p 9092:9092 --name kafka docker.io/mellonedain/kafka:latest

build:
	docker build -t docker.io/mellonedain/kafka .

push:
	docker push docker.io/mellonedain/kafka:latest

